### ISSUE TITLE
Doesn't work for cutscenes you haven't seen at least once before

### ISSUE THREAD

**Issue by AetherCollective** [KangasZ/SkipCutscene#1]
As the title says, doesn't work for any cutscene that you haven't seen at least once. Being forced to watch the cutscene in its entirety.

**Comment by KangasZ** [comment]
This does sound like a valid bug. However, it doesnt seem to be a bug that I'm worried about. The plugin is only for the three MSQ dungeons at level 50 and if it works the second time then I have no issue with it.

**Comment by AetherCollective** [comment]
Ngl kinda surprised I can close my own issue with the reason "not planned" /shrug
